### PR TITLE
update from root repository

### PR DESCRIPTION
**Pull request by Jared-Prime**
part of https://github.com/Fooda/foobot/issues/5

### CODE REVIEW

**Comment by ctailor2** [comment]
note - diff from https://github.com/miyagawa/hubot-standup/blob/f4387e07c3a417ff74b204bbef071b46df1cc1f8/src/scripts/standup.coffee

**Comment by ctailor2** [comment]
:+1:

**Comment by Jared-Prime** [comment]
Cool. Does it work? ( I didn't get a chance to try out the whole thing last
week)

**Comment by Jared-Prime** [comment]
can I haz mergy merge @DrMavenRebe

**Comment by DrMavenRebe** [comment]
:rocket:

**Pull request merged**
